name: unscrambler
version: 0.9.5
author: Frank Pepermans <frank@igindo.com>
description: A word unscrambler algorithm
homepage: https://github.com/frankpepermans/unscrambler
documentation: https://github.com/frankpepermans/unscrambler
dev_dependencies:
  benchmark_harness: any
  unittest: any
